name: Crop Recommendation CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t crop-recommendation:v1 .

      - name: Tag Docker Image
        run: |
          docker tag crop-recommendation:v1 \
          066971257562.dkr.ecr.ap-south-1.amazonaws.com/crop-recommendation:v1

      - name: Push Docker Image to ECR
        run: |
          docker push \
          066971257562.dkr.ecr.ap-south-1.amazonaws.com/crop-recommendation:v1


  deploy-to-ec2:

    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "Connected to EC2"

            echo "Logging into ECR..."

            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS --password-stdin \
            066971257562.dkr.ecr.ap-south-1.amazonaws.com

            echo "Pulling latest image..."

            docker pull \
            066971257562.dkr.ecr.ap-south-1.amazonaws.com/crop-recommendation:v1

            echo "Stopping old container..."

            docker stop crop-app || true

            echo "Removing old container..."

            docker rm crop-app || true

            echo "Starting new container..."

            docker run -d \
            -p 5000:5000 \
            --name crop-app \
            066971257562.dkr.ecr.ap-south-1.amazonaws.com/crop-recommendation:v1

            echo "Deployment completed!"