name: Crop Recommendation CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t crop-recommendation:v1 .

      - name: Tag Docker Image
        run: |
          docker tag crop-recommendation:v1 \
          066971257562.dkr.ecr.ap-south-1.amazonaws.com/crop-recommendation:v1

      - name: Push Docker Image to ECR
        run: |
          docker push \
          066971257562.dkr.ecr.ap-south-1.amazonaws.com/crop-recommendation:v1